---
spring.profiles: local

system:
  type: API_CLIENT
  name: bingoClient01
  domain: bingo-client01-local.javacafe.or.kr
  machineName: local-bingo-client01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: dev

system:
  type: API_CLIENT
  name: bingoClient01
  domain: bingo-client01-dev.javacafe.or.kr
  machineName: dev-bingo-client01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: staging

system:
  type: API_CLIENT
  name: bingoClient01
  domain: bingo-client01-stg.javacafe.or.kr
  machineName: stg-bingo-client01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: real

system:
  type: API_CLIENT
  name: bingoClient01
  domain: bingo-client01.javacafe.or.kr
  machineName: real-bingo-client01.ncl
  ip: 127.0.0.1
  listenQueueName:  


    