---
spring.profiles: local

system:
  type: SERVICE_USER
  name: bingoServiceUser01
  domain: bingo-su01-local.javacafe.or.kr
  machineName: local-bingo-su01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: dev

system:
  type: SERVICE_USER
  name: bingoServiceUser01
  domain: bingo-su01-dev.javacafe.or.kr
  machineName: dev-bingo-su01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: staging

system:
  type: SERVICE_USER
  name: bingoServiceUser01
  domain: bingo-su01-stg.javacafe.or.kr
  machineName: stg-bingo-su01.ncl
  ip: 127.0.0.1
  listenQueueName:  


---
spring.profiles: real

system:
  type: SERVICE_USER
  name: bingoServiceUser01
  domain: bingo-su01.javacafe.or.kr
  machineName: real-bingo-su01.ncl
  ip: 127.0.0.1
  listenQueueName:  


    