---
spring.profiles: local

system:
  name: bingoApiGateway01
  domain: bingog01-local.javacafe.or.kr
  machineName: local-bingo021.ncl
  ip: 127.0.0.1
  listenQueueName: bingoApiGateway01 


---
spring.profiles: dev

system:
  name: bingoApiGateway01
  domain: bingog01-dev.javacafe.or.kr
  machineName: dev-bingo021.ncl
  ip: 127.0.0.1
  listenQueueName: bingoApiGateway01 


---
spring.profiles: staging

system:
  name: bingoApiGateway01
  domain: bingog01-stg.javacafe.or.kr
  machineName: stg-bingo021.ncl
  ip: 127.0.0.1
  listenQueueName: bingoApiGateway01 


---
spring.profiles: real

system:
  name: bingoApiGateway01
  domain: bingog01.javacafe.or.kr
  machineName: real-bingo021.ncl
  ip: 127.0.0.1
  listenQueueName: bingoApiGateway01 


    